<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE5w5W46\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE5w5W46/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE5w5W46.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE5w5W46\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE5w5W46\App_KernelDevDebugContainer([
    'container.build_hash' => 'E5w5W46',
    'container.build_id' => '3f2338ec',
    'container.build_time' => 1663843254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE5w5W46');
