<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDJYY0Sk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDJYY0Sk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDJYY0Sk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDJYY0Sk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDJYY0Sk\App_KernelDevDebugContainer([
    'container.build_hash' => 'DJYY0Sk',
    'container.build_id' => '0b35768a',
    'container.build_time' => 1664953994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDJYY0Sk');
