<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtCt3Uk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtCt3Uk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLtCt3Uk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLtCt3Uk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLtCt3Uk\App_KernelDevDebugContainer([
    'container.build_hash' => 'LtCt3Uk',
    'container.build_id' => '4b44de49',
    'container.build_time' => 1664954352,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtCt3Uk');
